version: "3"
services: 
  auth-api: 
    build: .
    depends_on: 
      - postgres
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app:ro
    command: npm run dev
    environment: 
      - PORT = 3000
      - HOST_URL = http://localhost:4200
      - JWT_SECRET = MY_JWT_SECRET
      - NODE_ENV = development
      # Local
      - DB_HOST=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=1111
      - DB_DATABASE_NAME=postgres
      - DB_DATABASE_NAME_TEST=postgres_test
      - DB_PORT=5432
      #email
      - EMAIL_USER={{email}}
      - EMAIL_PASS={{password}}
      - EMAIL_HOST=smtp.hostinger.com
      - EMAIL_PORT=465

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111

  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
  
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
